/*
Copyright 2025 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RelatedResourceSpecApplyConfiguration represents a declarative configuration of the RelatedResourceSpec type for use
// with apply.
type RelatedResourceSpecApplyConfiguration struct {
	Identifier *string                                  `json:"identifier,omitempty"`
	Origin     *string                                  `json:"origin,omitempty"`
	Kind       *string                                  `json:"kind,omitempty"`
	Object     *RelatedResourceObjectApplyConfiguration `json:"object,omitempty"`
	Mutation   *ResourceMutationSpecApplyConfiguration  `json:"mutation,omitempty"`
}

// RelatedResourceSpecApplyConfiguration constructs a declarative configuration of the RelatedResourceSpec type for use with
// apply.
func RelatedResourceSpec() *RelatedResourceSpecApplyConfiguration {
	return &RelatedResourceSpecApplyConfiguration{}
}

// WithIdentifier sets the Identifier field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Identifier field is set to the value of the last call.
func (b *RelatedResourceSpecApplyConfiguration) WithIdentifier(value string) *RelatedResourceSpecApplyConfiguration {
	b.Identifier = &value
	return b
}

// WithOrigin sets the Origin field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Origin field is set to the value of the last call.
func (b *RelatedResourceSpecApplyConfiguration) WithOrigin(value string) *RelatedResourceSpecApplyConfiguration {
	b.Origin = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *RelatedResourceSpecApplyConfiguration) WithKind(value string) *RelatedResourceSpecApplyConfiguration {
	b.Kind = &value
	return b
}

// WithObject sets the Object field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Object field is set to the value of the last call.
func (b *RelatedResourceSpecApplyConfiguration) WithObject(value *RelatedResourceObjectApplyConfiguration) *RelatedResourceSpecApplyConfiguration {
	b.Object = value
	return b
}

// WithMutation sets the Mutation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mutation field is set to the value of the last call.
func (b *RelatedResourceSpecApplyConfiguration) WithMutation(value *ResourceMutationSpecApplyConfiguration) *RelatedResourceSpecApplyConfiguration {
	b.Mutation = value
	return b
}
