/*
Copyright 2025 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RelatedResourceSourceApplyConfiguration represents a declarative configuration of the RelatedResourceSource type for use
// with apply.
type RelatedResourceSourceApplyConfiguration struct {
	RelatedResourceSourceSpecApplyConfiguration `json:",inline"`
	Namespace                                   *RelatedResourceSourceSpecApplyConfiguration `json:"namespace,omitempty"`
}

// RelatedResourceSourceApplyConfiguration constructs a declarative configuration of the RelatedResourceSource type for use with
// apply.
func RelatedResourceSource() *RelatedResourceSourceApplyConfiguration {
	return &RelatedResourceSourceApplyConfiguration{}
}

// WithSelector sets the Selector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Selector field is set to the value of the last call.
func (b *RelatedResourceSourceApplyConfiguration) WithSelector(value *RelatedResourceSelectorApplyConfiguration) *RelatedResourceSourceApplyConfiguration {
	b.Selector = value
	return b
}

// WithReference sets the Reference field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reference field is set to the value of the last call.
func (b *RelatedResourceSourceApplyConfiguration) WithReference(value *RelatedResourceReferenceApplyConfiguration) *RelatedResourceSourceApplyConfiguration {
	b.Reference = value
	return b
}

// WithExpression sets the Expression field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Expression field is set to the value of the last call.
func (b *RelatedResourceSourceApplyConfiguration) WithExpression(value string) *RelatedResourceSourceApplyConfiguration {
	b.Expression = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *RelatedResourceSourceApplyConfiguration) WithNamespace(value *RelatedResourceSourceSpecApplyConfiguration) *RelatedResourceSourceApplyConfiguration {
	b.Namespace = value
	return b
}
