/*
Copyright 2025 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RelatedResourceObjectSpecApplyConfiguration represents a declarative configuration of the RelatedResourceObjectSpec type for use
// with apply.
type RelatedResourceObjectSpecApplyConfiguration struct {
	Selector  *RelatedResourceObjectSelectorApplyConfiguration  `json:"selector,omitempty"`
	Reference *RelatedResourceObjectReferenceApplyConfiguration `json:"reference,omitempty"`
	Template  *TemplateExpressionApplyConfiguration             `json:"template,omitempty"`
}

// RelatedResourceObjectSpecApplyConfiguration constructs a declarative configuration of the RelatedResourceObjectSpec type for use with
// apply.
func RelatedResourceObjectSpec() *RelatedResourceObjectSpecApplyConfiguration {
	return &RelatedResourceObjectSpecApplyConfiguration{}
}

// WithSelector sets the Selector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Selector field is set to the value of the last call.
func (b *RelatedResourceObjectSpecApplyConfiguration) WithSelector(value *RelatedResourceObjectSelectorApplyConfiguration) *RelatedResourceObjectSpecApplyConfiguration {
	b.Selector = value
	return b
}

// WithReference sets the Reference field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reference field is set to the value of the last call.
func (b *RelatedResourceObjectSpecApplyConfiguration) WithReference(value *RelatedResourceObjectReferenceApplyConfiguration) *RelatedResourceObjectSpecApplyConfiguration {
	b.Reference = value
	return b
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *RelatedResourceObjectSpecApplyConfiguration) WithTemplate(value *TemplateExpressionApplyConfiguration) *RelatedResourceObjectSpecApplyConfiguration {
	b.Template = value
	return b
}
