/*
Copyright 2025 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ResourceMutationSpecApplyConfiguration represents a declarative configuration of the ResourceMutationSpec type for use
// with apply.
type ResourceMutationSpecApplyConfiguration struct {
	Spec   []ResourceMutationApplyConfiguration `json:"spec,omitempty"`
	Status []ResourceMutationApplyConfiguration `json:"status,omitempty"`
}

// ResourceMutationSpecApplyConfiguration constructs a declarative configuration of the ResourceMutationSpec type for use with
// apply.
func ResourceMutationSpec() *ResourceMutationSpecApplyConfiguration {
	return &ResourceMutationSpecApplyConfiguration{}
}

// WithSpec adds the given value to the Spec field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Spec field.
func (b *ResourceMutationSpecApplyConfiguration) WithSpec(values ...*ResourceMutationApplyConfiguration) *ResourceMutationSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSpec")
		}
		b.Spec = append(b.Spec, *values[i])
	}
	return b
}

// WithStatus adds the given value to the Status field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Status field.
func (b *ResourceMutationSpecApplyConfiguration) WithStatus(values ...*ResourceMutationApplyConfiguration) *ResourceMutationSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithStatus")
		}
		b.Status = append(b.Status, *values[i])
	}
	return b
}
