/*
Copyright 2025 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ResourceRegexMutationApplyConfiguration represents a declarative configuration of the ResourceRegexMutation type for use
// with apply.
type ResourceRegexMutationApplyConfiguration struct {
	Path        *string `json:"path,omitempty"`
	Pattern     *string `json:"pattern,omitempty"`
	Replacement *string `json:"replacement,omitempty"`
}

// ResourceRegexMutationApplyConfiguration constructs a declarative configuration of the ResourceRegexMutation type for use with
// apply.
func ResourceRegexMutation() *ResourceRegexMutationApplyConfiguration {
	return &ResourceRegexMutationApplyConfiguration{}
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *ResourceRegexMutationApplyConfiguration) WithPath(value string) *ResourceRegexMutationApplyConfiguration {
	b.Path = &value
	return b
}

// WithPattern sets the Pattern field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pattern field is set to the value of the last call.
func (b *ResourceRegexMutationApplyConfiguration) WithPattern(value string) *ResourceRegexMutationApplyConfiguration {
	b.Pattern = &value
	return b
}

// WithReplacement sets the Replacement field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replacement field is set to the value of the last call.
func (b *ResourceRegexMutationApplyConfiguration) WithReplacement(value string) *ResourceRegexMutationApplyConfiguration {
	b.Replacement = &value
	return b
}
