/*
Copyright 2024 The Kubermatic Kubernetes Platform contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "k8c.io/servlet/sdk/apis/services/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"

	scheme "k8c.io/servlet/sdk/clientset/versioned/scheme"
)

// PublishedResourcesGetter has a method to return a PublishedResourceInterface.
// A group's client should implement this interface.
type PublishedResourcesGetter interface {
	PublishedResources() PublishedResourceInterface
}

// PublishedResourceInterface has methods to work with PublishedResource resources.
type PublishedResourceInterface interface {
	Create(ctx context.Context, publishedResource *v1alpha1.PublishedResource, opts v1.CreateOptions) (*v1alpha1.PublishedResource, error)
	Update(ctx context.Context, publishedResource *v1alpha1.PublishedResource, opts v1.UpdateOptions) (*v1alpha1.PublishedResource, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, publishedResource *v1alpha1.PublishedResource, opts v1.UpdateOptions) (*v1alpha1.PublishedResource, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.PublishedResource, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.PublishedResourceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PublishedResource, err error)
	PublishedResourceExpansion
}

// publishedResources implements PublishedResourceInterface
type publishedResources struct {
	*gentype.ClientWithList[*v1alpha1.PublishedResource, *v1alpha1.PublishedResourceList]
}

// newPublishedResources returns a PublishedResources
func newPublishedResources(c *ServicesV1alpha1Client) *publishedResources {
	return &publishedResources{
		gentype.NewClientWithList[*v1alpha1.PublishedResource, *v1alpha1.PublishedResourceList](
			"publishedresources",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1alpha1.PublishedResource { return &v1alpha1.PublishedResource{} },
			func() *v1alpha1.PublishedResourceList { return &v1alpha1.PublishedResourceList{} }),
	}
}
