/*
Copyright 2024 The Kubermatic Kubernetes Platform contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SourceResourceDescriptorApplyConfiguration represents a declarative configuration of the SourceResourceDescriptor type for use
// with apply.
type SourceResourceDescriptorApplyConfiguration struct {
	APIGroup *string `json:"apiGroup,omitempty"`
	Version  *string `json:"version,omitempty"`
	Kind     *string `json:"kind,omitempty"`
}

// SourceResourceDescriptorApplyConfiguration constructs a declarative configuration of the SourceResourceDescriptor type for use with
// apply.
func SourceResourceDescriptor() *SourceResourceDescriptorApplyConfiguration {
	return &SourceResourceDescriptorApplyConfiguration{}
}

// WithAPIGroup sets the APIGroup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIGroup field is set to the value of the last call.
func (b *SourceResourceDescriptorApplyConfiguration) WithAPIGroup(value string) *SourceResourceDescriptorApplyConfiguration {
	b.APIGroup = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *SourceResourceDescriptorApplyConfiguration) WithVersion(value string) *SourceResourceDescriptorApplyConfiguration {
	b.Version = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *SourceResourceDescriptorApplyConfiguration) WithKind(value string) *SourceResourceDescriptorApplyConfiguration {
	b.Kind = &value
	return b
}
